# Site settings
title: kisuhy.github.io
name: kisuhy.github.io # your name
email: jeremy0878@hanyang.ac.kr # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: /
url: "https://itisbenjamin.github.io" # the base hostname & protocol for your site
twitter_username: itisbenjamin1 # your Twitter username
github_username: kisuhy # your Github username
disqus_username: itisbenjamin # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
